# Generated by Django 4.2.4 on 2023-09-01 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_district_state_fk_alter_user_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=256, verbose_name='Hall Name')),
                ('business_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Hall Renter'), (2, 'Catress')], null=True, verbose_name='Business Type')),
                ('premium', models.BooleanField(blank=True, null=True, verbose_name='Premium')),
                ('economical', models.BooleanField(blank=True, null=True, verbose_name='Economical')),
                ('budget', models.BooleanField(blank=True, null=True, verbose_name='Budget')),
                ('business_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hall Address')),
                ('contect_no', models.CharField(max_length=13, verbose_name='Contect Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country', verbose_name='Country FK')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.district', verbose_name='District FK')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state', verbose_name='State FK')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_renter', to=settings.AUTH_USER_MODEL, verbose_name='Vender')),
            ],
        ),
    ]
