# Generated by Django 4.2.5 on 2023-09-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="hall_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hall_package",
                to="package.hall",
                verbose_name="Hall",
            ),
        ),
    ]
