# Generated by Django 4.2.4 on 2023-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='business',
            name='economical',
        ),
        migrations.RemoveField(
            model_name='business',
            name='premium',
        ),
    ]
