# Generated by Django 4.2.4 on 2023-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_remove_business_budget_remove_business_economical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=256, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hall Renter'), (2, 'Catress')], default=1, verbose_name='Business Type'),
            preserve_default=False,
        ),
    ]
