# Generated by Django 4.2.4 on 2023-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_business_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Business Name'),
        ),
    ]
