# Generated by Django 4.2.4 on 2023-08-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_country_states_district_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='states',
            new_name='state',
        ),
    ]
