# Generated by Django 4.2.4 on 2023-09-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_states_state_rename_states_state_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='user.state', verbose_name='State FK'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Vendor')], verbose_name='User Role'),
        ),
    ]
